# spell-checker: ignore XMLDOC gableroux OPTOUT peaceiris
name: Build

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - Project

        unityVersion:
          - 2019.4.14f1

        targetPlatform:
          - WebGL

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-

      - uses: game-ci/unity-builder@v1.5
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}

      - uses: peaceiris/actions-gh-pages@v3.6.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/${{ matrix.targetPlatform }}/${{ matrix.targetPlatform }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.targetPlatform }}-Build
          path: build

