name: Build

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        unity-tag: [2019.4.14f1]
        dotnet-version: ['5.0.100']

    runs-on: ubuntu-latest
    container: docker://gableroux/unity3d:${{ matrix.unity-tag }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.6.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - run: dotnet fsi Build.fsx

      - uses: actions/upload-artifact@v2
        with:
          name: WindowsBuild
          path: Windows
